jwt:
  secret:
    access: LejjnLZua6SlR7eZXByD2+9M5P+dYxK3IlfA6XgPksuXijiXMAcpulI03o2Vq+PjYENhgTJGXLNm7YS4f1+IMw==
    refresh: cRO8f7Q/HaE/X1QjxAHYL8Dm5qkTI68WiNi9elE1NFqsL2up0RlZn/e7aD2R5i8cMvCksBEDhUAOZAhsypQaXw==
server:
  port: 9000
springdoc:
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: alpha
spring:
  h2:
    console:
      enabled: true
      settings:
        trace: false
---
spring:
  profiles:
    active: prod
---
spring:
  jackson:
    mapper:
      default-view-inclusion: true
  flyway:
    enabled: true
  sql:
    init:
      mode: never
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: false
    show-sql: true
    hibernate:
      id:
        new_generator_mappings: true
      ddl-auto: none
  config:
    activate:
      on-profile: local
---
spring:
  jackson:
    mapper:
      default-view-inclusion: true
  flyway:
    enabled: false
  datasource:
    url: jdbc:postgresql://cornelius.db.elephantsql.com:5432/
    username: umakpocc
    password: L6ibD7NSX8QOurP8y965FfnziXZSZc6B
  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        generate_statistics: false
    show-sql: false
  config:
    activate:
      on-profile: prod
